#pragma once

// TODO these are custom numbers now. May need to be changed if compiling for some userland

#define E2BIG           1
#define EACCES          2
#define EADDRINUSE      3
#define EADDRNOTAVAIL   4
#define EAFNOSUPPORT    5
#define EAGAIN          6
#define EALREADY        7
#define EBADF           8
#define EBADMSG         9
#define EBUSY           10
#define ECANCELED       11
#define ECHILD          12
#define ECONNABORTED    13
#define ECONNREFUSED    14
#define ECONNRESET      15
#define EDEADLK         16
#define EDESTADDRREQ    17
#define EDOM            18
#define EEXIST          19
#define EFAULT          20
#define EFBIG           21
#define EHOSTUNREACH    22
#define EIDRM           23
#define EILSEQ          24
#define EINPROGRESS     25
#define EINTR           26
#define EINVAL          27
#define EIO             28
#define EISCONN         29
#define EISDIR          30
#define ELOOP           31
#define EMFILE          32
#define EMLINK          33
#define EMSGSIZE        34
#define ENAMETOOLONG    35
#define ENETDOWN        36
#define ENETRESET       37
#define ENETUNREACH     38
#define ENFILE          39
#define ENOBUFS         40
#define ENODEV          41
#define ENOENT          42
#define ENOEXEC         43
#define ENOLCK          44
#define ENOLINK         45
#define ENOMEM          46
#define ENOMSG          47
#define ENOPROTOOPT     48
#define ENOSPC          49
#define ENOSYS          50
#define ENOTCONN        51
#define ENOTDIR         52
#define ENOTEMPTY       53
#define ENOTRECOVERABLE 54
#define ENOTSOCK        55
#define ENOTSUP         56
#define ENOTTY          57
#define ENXIO           58
#define EOPNOTSUPP      59
#define EOVERFLOW       60
#define EOWNERDEAD      61
#define EPERM           62
#define EPIPE           63
#define EPROTO          64
#define EPROTONOSUPPORT 65
#define EPROTOTYPE      66
#define ERANGE          67
#define EROFS           68
#define ESPIPE          69
#define ESRCH           70
#define ETIMEDOUT       71
#define ETXTBSY         72
#define EWOULDBLOCK     73
#define EXDEV           74
